### ISSUE TITLE
I pasted the wrong API key. Where to change it?

### ISSUE THREAD

**Issue by frankhommers** [SimiaCryptus/intellij-aicoder#11]
I pasted the wrong API key, and now it doesn't ask me for a new correct one.
Where can I change this?

**Comment by MauRiEEZZZ** [comment]
Open settings (command + ,)
search for AI Coder
You can find it under Tools
<img width="767" alt="image" src="https://user-images.githubusercontent.com/9781801/212915571-4f87c8e7-cb80-418d-8e54-58c582be8959.png">

**Comment by frankhommers** [comment]
Thanks, it works now
