### ISSUE TITLE
Unbalanced Input warning

### ISSUE THREAD

**Issue by zoltansuto** [SimiaCryptus/intellij-aicoder#12]
@acharneski do you have any idea why I'm getting this error?
What do you need to investigate this?
I'm selecting a code and choose add code comments and I'm getting the above error
also enabling dev tools creates a huge window, I can't see the bottom of it or resize it, nor scroll in it

![image](https://user-images.githubusercontent.com/18262144/212922778-652cc3b7-6287-4aeb-bce5-6a1af73fb9b5.png)

Please, let me know what you need to investigate this :)

**Comment by acharneski** [comment]
That's a bit confusing, and I think this should be improved.

Explanation: The text generated *started* an unbalanced bracket pair, such as '}' without a preceding '{'

**Comment by acharneski** [comment]
This has been fixed in the newer versions
