### ISSUE TITLE
suggestion: add used programming language as variable in system role

### ISSUE THREAD

**Issue by noone-silent** [SimiaCryptus/intellij-aicoder#129]
Currently the assistant always generates java code. For a PHP project we have to select the code as context and write the prompt our self.

What would be nice, would be a detection based on the `mime type` of the file. For example in the chat you display:

`Selected code from file:///some/path/to/file.php`

Maybe you could use that and change the prompt to `Add test case for this code in language $usedLanguage.`

**Comment by acharneski** [comment]
There is already language logic like that, this sounds like a bug. If this is still happening in the most recent version, can you include more detail such as what action you were running?
