### ISSUE TITLE
1.2.25 installing plugin from disk fails (Phpstorm, ubuntu)

### ISSUE THREAD

**Issue by suzol10** [SimiaCryptus/intellij-aicoder#131]
Phpstorm PhpStorm 2023.3.4
Ubuntu 22.04
unknown plugins com.intellij.java, org.jetbrains.kotlin

![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/56600318/70bd28be-e92e-4cdd-add1-f3fa274e22c3)
![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/56600318/b6a3341b-0a3f-45d4-8450-738c7356d5ec)

**Comment by acharneski** [comment]
OMG thanks for the report! This is fixed in 1.4.1, being release now
