### ISSUE TITLE
Customize Menus and Toolbars stopped working when plugin is active

### ISSUE THREAD

**Issue by steigr** [SimiaCryptus/intellij-aicoder#21]
When opening "Customize Menus and Toolbars..." an exception is thrown:

```
cannot reset configurable

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'e' of com/github/simiacryptus/aicoder/util/ComputerLanguage.getComputerLanguage must not be null
```

**Comment by acharneski** [comment]
I just released a new version, so this may be fixed... but cannot be sure without a stack trace.

If this continues, please let me know the rest of the message and I can fix. Thanks!

**Comment by acharneski** [comment]
Closing inactive ticket
