### ISSUE TITLE
How to use gpt-4?

### ISSUE THREAD

**Issue by mdev88** [SimiaCryptus/intellij-aicoder#36]
Hello,

I have been granted API access to gpt-4 beta and I wanted to know if it was possible to use it with this plugin.

What values should I choose in the 3 models fields (chat, completion, edit)?

Thanks!

**Comment by mdev88** [comment]
I see that gpt-4 is only intended as a chat model, so I can only choose gpt-4 for that model, and keep using davinci for the other two uses. Right?

**Comment by acharneski** [comment]
So this is complicated.... but it will be addressed in the next release.

For now, you CAN use GPT4 by selecting it as the "chat model", but the only things that use it currently are "Chat Append Text" (personally this is my most used function, and will get some polish soon) and "Generate Project".... which, damn, I just looked at and seems to have some issues with the current release. Sigh!

**Comment by mdev88** [comment]
No problem, thank you for addressing this issue. Looking forward to future improvements!
