### ISSUE TITLE
"Completion Request" window before any completion

### ISSUE THREAD

**Issue by sgavka** [SimiaCryptus/intellij-aicoder#37]
This window appears before each completion request:

![image](https://user-images.githubusercontent.com/5457405/229190011-919a8c3f-eb95-48f9-8970-b7f671598c28.png)

**Comment by acharneski** [comment]
Wow. The button text is a known bug but the max tokens field is definitely bad. Thank you for the report, will look into it. Can you confirm you have the most recent release? (1.0.19)

Also, is that your complaint? The reason the dialog appears at all is that you have the "Developer Tools" checkbox clicked in settings. This is the main "developer tool" :-)

**Comment by sgavka** [comment]
@acharneski Yes, I have the latest version of the plugin.

Oh, yes, my main problem was that window. So, after you said I could just uncheck the checkbox, it helped.
