### ISSUE TITLE
"You exceeded your current quota, please check your plan and billing details."

### ISSUE THREAD

**Issue by sgavka** [SimiaCryptus/intellij-aicoder#41]
This error appeared after I tried to update my API key, also I had already deleted my old key from the OpenAI system, which caused the issue. Initially, the error showed that I had an incorrect API key, but it displayed my old key. Now, despite paying for the pro plan, the error still appears.

![image](https://user-images.githubusercontent.com/5457405/231600346-cd6b8ff0-38af-4aa3-a808-d3fa69b33f47.png)

**Comment by sgavka** [comment]
Hmm, now it works. Before, I only had ChatGPT-Plus, but now I purchased a subscription here: https://platform.openai.com/account/billing/overview and now it works. I had no clue that was the problem. :)

**Comment by acharneski** [comment]
Huh... thanks for the report, I guess! Closing!
