### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by sgavka** [SimiaCryptus/intellij-aicoder#51]
I have a few suggestions for your very useful plugin:

1. **Instead of immediately pasting the generated text into the editor, why not open a diff tool to show the changes?** This would make it easier to review, accept, or reject changes before committing them to the codebase.

2. **Another beneficial feature would be the ability to edit the built-in prompts.** Sometimes the default prompts may not be suitable for a specific use case, so being able to tweak them would be a significant time-saver.

3. Finally, **it would be great if users could add their personal prompts with custom shortcuts**. This would allow developers to create their own library of frequently used phrases and code snippets, saving even more time and reducing the risk of errors.

Also, I appreciate the feature of input before code editing that allows extending the built-in prompt.

**Comment by acharneski** [comment]
1. I've thought of this too, and something like this may be added in the future. UI programming the intellij interface is still pretty hard for me to figure out. :-)
2. I used to have a feature for this, and I may add it back in the future. I removed it to ease the development work in recent improvements.
3. There is a most-recently-used list for custom edit actions. Is there a specific feature you'd like this on?

**Comment by sgavka** [comment]
@acharneski 

I would like to add custom items to the AI Coder context menu with a full prompt (it seems that a part of the prompt is hidden) and custom shortcuts. For instance, I want to create prompts such as making a code review for selected code by adding comments with propositions or performing a code refactor on selected code to make it more readable and faster. Additionally, I would like to have an additional dialog where I can add more specific queries on specific requests, such as "do not change anything in SQL." Essentially, I am looking for a plugin that can construct actions with AI on my code. I understand that this may not be a simple task. :)

thx for your work

**Comment by acharneski** [comment]
In the next release, which should be out on monday, will have some new features that should answer these use cases.

Various actions (which will increase as I port them to the new format) will be both editable and cloneable for a high level of customization. You will be able to edit the action source code (in groovy) to customize nearly anything about an action!

We have a large amount of actions so it will take awhile to port them all to groovy, but this should provide a framework for a high level of user customization!

**Comment by acharneski** [comment]
Closing as these suggestions have largely been implemented. Thanks for the discussion!
