### ISSUE TITLE
Cancelation of action

### ISSUE THREAD

**Issue by sgavka** [SimiaCryptus/intellij-aicoder#55]
Sometimes certain actions take too long to complete, and when I try to cancel them, it can freeze for an extended period of time (5-10 minutes). In some cases, I need to restart the IDE. 
![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/5457405/45a380f2-058f-4ad5-9558-0a901e50072c)

**Comment by acharneski** [comment]
This should be fixed in 1.1.4, which will hopefully be approved today.

**Comment by sgavka** [comment]
![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/5457405/be0b1271-05ab-4eae-a96e-acbb3b57b07f)
Here's an example of a case where I tried to edit the code, but after some processing time, it returned an error.

**Comment by acharneski** [comment]
This should be fixed; closing
