### ISSUE TITLE
Local LLM

### ISSUE THREAD

**Issue by VictorUceda** [SimiaCryptus/intellij-aicoder#56]
Is there a possibility to adapt the plugin to support calling a locally executed LLM?

**Comment by acharneski** [comment]
I'd love to support this and it is something I'm keeping an eye on, but there are a number of challenges and currently the models you could run locally wouldn't be smart enough to be all that functional in a plugin like this.

I'll keep this open as a feature request

**Comment by VictorUceda** [comment]
It could be very interesting to leave the freedom to the user to configure the API address, so that they can run a local server with the LLM running in the background. It would be the most similar way to support this vs the openai api.

Obviously the complexity of the model depends on the user's choise and if it is not smart enough, it is the user's responsibility.

**Comment by acharneski** [comment]
That's actually a great idea! The API base will always be configurable.

**Comment by acharneski** [comment]
Great discussion, but closing ticket since it outlines a strategy to support this feature without any code change to this plugin.
