### ISSUE TITLE
Wont process any request 

### ISSUE THREAD

**Issue by msmith624** [SimiaCryptus/intellij-aicoder#59]
Version 1.1.4
When I try to use any of the commands, the add-on freezes. 
![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/13894781/d0cf2cfe-d981-498a-ad0d-2804c8804fcb)

When I try to cancel the command I get an error 
![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/13894781/def019b7-db6e-424a-9eb6-eb70ffa9e36b)

**Comment by acharneski** [comment]
Does this only affect the "chat with code" or "skyenet" features? I'll be honest, I haven't tested those in the past couple releases, they are still experimental features and need to be enabled in settings.

**Comment by acharneski** [comment]
Please try again! Many fixes are out and this seems to work again.
