### ISSUE TITLE
Action Editor problem

### ISSUE THREAD

**Issue by sgavka** [SimiaCryptus/intellij-aicoder#63]
Then I restart PHPStorm in Editor Actions setting was empty.
After I try to perform some actions in some file appears it:
![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/5457405/afd407b2-f4e7-42b4-86cb-cceb1e1f51e1)

It is all actions that must be here? I can't find Edit code action.

**Comment by acharneski** [comment]
This is known and fixed along with another couple critical bugs stopping any new custom actions from actually working. I expect the fixed version to be available tomorrow.

**Comment by acharneski** [comment]
This, being a new feature, may have more issues, and please share them! However, this is fixed, so closing. Thanks for the report!

Note: This isn't all actions. Only ones I've ported to Goovy. However, with 1.2.4, it includes most actions.
