### ISSUE TITLE
CPU high usage

### ISSUE THREAD

**Issue by sgavka** [SimiaCryptus/intellij-aicoder#81]
In PHPStorm and PyCharm I have problem with the plugin, it use a lot of CPU then I manipulate text (like multiple pointers, etc.).
I think it is because of token counter functional that was added before, it try to count the tokens after every change in code.
I hope you can fix it, because now I can't use the plugin at all.
Thanks.

**Comment by sgavka** [comment]
Also it user a lot of CPU then i start autoformat code or fix imports.

**Comment by acharneski** [comment]
Thank you for the report! I have made a fix, and if you like, you will be able to download it from the "releases" section here on github soon. (Needs to go through release pipeline, ~1 hour)

It should be approved by JetBrains on Monday for auto-upgrading.

Thanks for mentioning multiple pointers. I don't ever use them, but the plugin should properly account for them.... currently just picks the first cursor. I'll keep this ticket open to track that issue.
