### ISSUE TITLE
"Ask a question about the code" option should not lock the whole interface.

### ISSUE THREAD

**Issue by Darkshadenl** [SimiaCryptus/intellij-aicoder#85]
Title says it all. 

When selecting code and selecting "Ask a question about the code", and little window appears in which to ask the question.
After selecting 'OK' the UI locks and only the loading window is available for use.

This is not a nice user experience.

**Comment by acharneski** [comment]
The whole "open a webserver" thing is a weird, hacky integration. I wanted to prevent the user from accidentally having a bunch of dead servers taking up IDE resources. However, agreed this could be improved. Suggestions welcome. Keeping this open to track.

**Comment by acharneski** [comment]
This has been improved with release 1.2.14, which is out for approval now.
