### ISSUE TITLE
Suggestion: AI Coder -> Generate Pytest

### ISSUE THREAD

**Issue by perweij** [SimiaCryptus/intellij-aicoder#89]
I find it useful to have AI Coder generate a pytest for the selected function.

Right now I do it like this:
 1. Mark the whole function
 2. AI Coder -> Edit Code, and use prompt "Write a pytest function for this code which tests various aspects"
 3. As expected the generated pytest function is inserted directly into the code buffer after the marked function. 
 4. I cut the inserted code, navigate to tests/.../test_<modulename>.py, and paste the code there

As it is so convenient to generate pytests with AI Coder, I was thinking if it would be possible to create some sort of function to generate a pytest for a marked function, and have it inserted directly into a test_-file in the project structure.

**Comment by acharneski** [comment]
There is also a context menu on the file itself in the project view. You should be able to use "Create Analogue File" to process the whole file and create a new file based on the directive. It is quite good at test generation, so long as the token count doesn't become an issue.
