### ISSUE TITLE
Don't let it be the top item in context menu when right clicking a file/folder in Intellij Project Explorer

### ISSUE THREAD

**Issue by chenjianjx** [SimiaCryptus/intellij-aicoder#93]
As you can see,  it's at the top above `New` 
![image](https://github.com/SimiaCryptus/intellij-aicoder/assets/877737/40f0ed5f-1d34-4107-b5d4-cf58e1bbbecd)

Long-time Intellij users have been used to the fact that `New` is top menu item in this case.   With it being the 2nd top one, the efficiency is reduced a lot.   Used lots of plugins.  None of them takes the top position. 

I suggest we let it be the 2nd menu item.

**Comment by acharneski** [comment]
Thanks for the feedback! This change has been made and will be out with the next release.
